# Generated by Django 5.0.4 on 2024-05-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='User', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
