# Generated by Django 5.0.4 on 2024-05-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpermissions_alter_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('manage_users', 'Manage Users')], 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
