# Generated by Django 5.0.4 on 2024-05-29 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
