# Generated by Django 5.0.4 on 2024-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Client', 'Client')], max_length=50),
        ),
    ]
