# Generated by Django 5.0.4 on 2024-05-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name': 'Invoices', 'verbose_name_plural': 'Invoices'},
        ),
    ]
