# Generated by Django 5.0.4 on 2024-05-14 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_cases_review_date_communications'),
        ('clients', '0005_clients_notes'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=6)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('term', models.CharField(choices=[('On Reciept', 'on_reciept'), ('7 Days', '7_days'), ('14 Days', '14_days'), ('30 Days', '30_days'), ('Custom', 'custom')], max_length=64)),
                ('amount', models.FloatField()),
                ('vat', models.FloatField()),
                ('total_due', models.FloatField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.cases')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
