# Generated by Django 5.0.4 on 2024-05-14 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clients_status'),
        ('invoices', '0002_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.invoicecode'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Sent', 'sent'), ('Not Sent', 'not_sent')], default='Not Sent', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='term',
            field=models.CharField(choices=[('On Reciept', 'on_reciept'), ('7 Days', '7_days'), ('14 Days', '14_days'), ('30 Days', '30_days'), ('Custom', 'custom')], default='On Reciept', max_length=64),
        ),
    ]
