# Generated by Django 5.0.4 on 2024-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoices_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
