# Generated by Django 5.0.4 on 2024-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoices_date_due_invoices_invoice_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_code',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='term',
            field=models.CharField(choices=[('On Reciept', 'On Reciept'), ('7 Days', '7 days'), ('14 Days', '14 days'), ('30 Days', '30 days'), ('Custom', 'Custom')], default='On Reciept', max_length=64),
        ),
    ]
