# Generated by Django 5.0.4 on 2024-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoices_invoice_code_alter_invoices_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='case_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='case_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='case_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
