# Generated by Django 5.0.4 on 2024-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoices_case_address_invoices_case_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='notes',
            field=models.TextField(),
        ),
    ]
