# Generated by Django 5.0.4 on 2024-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoices_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
