# Generated by Django 5.0.4 on 2024-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoices_invoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.CharField(max_length=6, verbose_name='Invoice No'),
        ),
    ]
