# Generated by Django 5.0.4 on 2024-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoices_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Invoice No'),
        ),
    ]
