# Generated by Django 5.0.4 on 2024-05-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoices_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_due',
            field=models.FloatField(default='0.00'),
        ),
    ]
