# Generated by Django 5.0.4 on 2024-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoices_amount_alter_invoices_total_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=19),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=19),
        ),
    ]
