# Generated by Django 5.0.4 on 2024-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_invoices_amount_alter_invoices_total_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='term',
            field=models.CharField(choices=[('On Receipt', 'On Receipt'), ('7 Days', '7 days'), ('14 Days', '14 days'), ('30 Days', '30 days'), ('Custom', 'Custom')], default='On Reciept', max_length=64),
        ),
    ]
