# Generated by Django 5.0.4 on 2024-07-16 09:14

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('case_name', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=240, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('assigned', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cases',
                'verbose_name_plural': 'Cases',
                'permissions': [('can_view_cases', 'View Case'), ('can_edit_cases', 'Edit Case')],
            },
        ),
        migrations.CreateModel(
            name='CaseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Case Types',
                'verbose_name_plural': 'Case Types',
            },
        ),
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
