# Generated by Django 5.0.4 on 2024-05-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetypes',
            name='short_code',
        ),
    ]
