# Generated by Django 5.0.4 on 2024-05-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='invoice_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicecode'),
        ),
        migrations.AddField(
            model_name='cases',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.casetypes'),
        ),
        migrations.AddField(
            model_name='communications',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.cases'),
        ),
    ]
