# Generated by Django 5.0.4 on 2024-05-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_casetypes_short_code'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='invoice_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicecode'),
        ),
    ]
