# Generated by Django 5.0.4 on 2024-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_cases_invoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='address',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
