# Generated by Django 5.0.4 on 2024-05-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_cases_review_date_communications'),
        ('clients', '0006_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clients'),
        ),
    ]
