# Generated by Django 5.0.4 on 2024-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('mobile', models.IntegerField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=124)),
                ('type', models.CharField(choices=[('Buisness', 'Buisness'), ('Personal', 'Personal')], default='Business', max_length=10)),
                ('building_number', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=64)),
                ('address_2', models.CharField(max_length=64)),
                ('address_3', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('post_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
