# Generated by Django 5.0.4 on 2024-05-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'permissions': [('can_view_clients', 'View Clients'), ('can_edit_clients', 'Edit Clients')], 'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
    ]
