# Generated by Django 5.0.4 on 2024-06-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='has_portal_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='portal_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type',
            field=models.CharField(choices=[('Buisness', 'Buisness'), ('Individual', 'Individual')], default='Business', max_length=10),
        ),
    ]
