# Generated by Django 5.0.4 on 2024-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_options_alter_clients_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
