# Generated by Django 5.0.4 on 2024-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_has_portal_access_clients_portal_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_reference',
            field=models.CharField(default='Temp', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
