# Generated by Django 5.0.4 on 2024-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_mobile_alter_clients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
