# Generated by Django 5.0.4 on 2024-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clients_client_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_reference',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
