# Generated by Django 5.0.4 on 2024-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clients_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
    ]
